### ISSUE TITLE
Package as a zip/tar distribution

### ISSUE THREAD

**Issue by oconnormi** [codice/acdebugger#18]
### Description

Add a distribution zip/tar archive that contains distribution specific bin scripts. This way the acdebugger could be installed and run like a normal command instead of via `java -jar`

**Comment by coyotesqrl** [comment]
Might want to switch over to Gradle for the build prior to doing this. That would make it trivially easy to generate OS-specific scripts.

**Comment by paouelle** [comment]
Also careful not to package tools.jar as we currently do in the jar with dependencies as Java should not be redistributed this way.
