### ISSUE TITLE
Acdebugger behaves incorrectly when working with bundle fragments

### ISSUE THREAD

**Issue by brjeter** [codice/acdebugger#40]
### Description
Acdebugger appears to look at the bundle's symbolic name for deciding what permissions it has, displaying that bundle's info, etc. This does not align with how the security manager works. The security manager uses that bundle's artifactId as the key.

### Steps to Reproduce

1. Debug an operation with a call stack that includes:
- bundle A which does **not have the necessary permission** (thus triggering the acdebugger) and
- bundle B which **has the necessary permission**, but has a symbolic name that's different than the artifactId [Example](https://github.com/ops4j/org.ops4j.pax.web/blob/master/pax-web-jetty/pom.xml#L51)

Note: If it's easier than artificially creating this scenario, this will happen on DDF 2.13.x as of [commit](https://github.com/codice/ddf/commit/d8f00c3f837291fdc05103449f522fc57ed1abed). Steps:
- Install DDF with the minimum profile
- Edit the Web Context Policy Manager config under Security
- Change "Authentication Types" from `/=IDP|GUEST` to `/=PKI|GUEST`
- Go to `https://localhost:8993/login/` and attempt to login.
- acdebugger should fail, saying this is the needed solution even though `pax-web-jetty` (the artifactId) already has the needed permission
```
AC Debugger:     Solution:
AC Debugger:     {
AC Debugger:         Add the following permission block to the appropriate policy file:
AC Debugger:             grant codeBase "file:/org.ops4j.pax.web.pax-web-jetty/security-rest-authn-endpoint" {
AC Debugger:                 permission java.io.FilePermission "${/}ddf-instances${/}clockard${/}dib-4.6.3-SNAPSHOT${/}etc${/}ws-security${/}server${/}signature.properties", "read";
AC Debugger:             }
AC Debugger:     }
```
#### Expected behavior:
The acdebugger should only provide output saying bundle A needs the permission

#### Actual behavior:
The acdebugger will provide output saying that both bundles A and B need the permission

#### Reproduces how often:
Every time

### Version
1.7

**Comment by paouelle** [comment]
It turns out that the issue was actually related to the fact that the bundle was a fragment and the logic to compute the list of domains was coming up with the host bundle as opposed to the fragment bundle as does the security manager.
